# Generated by Django 4.2.9 on 2026-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_id', models.CharField(db_column='customer_id', max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('contact', models.CharField(db_column='contact', max_length=255)),
            ],
            options={
                'db_table': 'tbl_customerinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('no', models.CharField(db_column='no', max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_column='customer_id', max_length=50)),
            ],
            options={
                'db_table': 'tbl_itemcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityMaster',
            fields=[
                ('item_no', models.CharField(db_column='item_no', max_length=50, primary_key=True, serialize=False)),
                ('opportunity_id', models.CharField(blank=True, db_column='id', max_length=50, null=True)),
                ('last_ecn_no', models.CharField(blank=True, db_column='no_2', max_length=50, null=True)),
                ('project_name_db', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, db_column='customerid', max_length=50, null=True)),
                ('customer_name_db', models.CharField(blank=True, db_column='customername', max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, db_column='contactname', max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, db_column='contact_no', max_length=50, null=True)),
                ('salesperson_code', models.CharField(blank=True, db_column='salesperson_code', max_length=50, null=True)),
                ('sales_cycle_code', models.CharField(blank=True, db_column='sales_cycle_code', max_length=50, null=True)),
                ('creation_date', models.DateField(blank=True, db_column='creation_date', null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=50, null=True)),
                ('reason', models.CharField(blank=True, db_column='reason', max_length=100, null=True)),
                ('segment_no', models.CharField(blank=True, db_column='segment_no', max_length=50, null=True)),
                ('segment_desc', models.CharField(blank=True, db_column='segment_description', max_length=255, null=True)),
                ('part_name', models.CharField(blank=True, db_column='part_name', max_length=255, null=True)),
                ('opp_received_date', models.DateField(blank=True, db_column='opportunity_received_date', null=True)),
                ('sop_date', models.DateField(blank=True, db_column='sop_date', null=True)),
                ('drawing_rev', models.CharField(blank=True, db_column='drawing_revision_no', max_length=50, null=True)),
                ('application', models.CharField(blank=True, db_column='application', max_length=100, null=True)),
                ('business', models.CharField(blank=True, db_column='business', max_length=100, null=True)),
                ('plant_loc', models.CharField(blank=True, db_column='voss_plant_location', max_length=100, null=True)),
                ('status_date', models.DateField(blank=True, db_column='status_date', null=True)),
                ('sales_goahead', models.DateField(blank=True, db_column='sales_goahead_date_for_tool', null=True)),
                ('vol1', models.CharField(blank=True, db_column='annual_volume', max_length=50, null=True)),
                ('year1', models.CharField(blank=True, db_column='annual_volume_year', max_length=50, null=True)),
                ('vol2', models.CharField(blank=True, db_column='annual_volume_2', max_length=50, null=True)),
                ('year2', models.CharField(blank=True, db_column='annual_volume_year_2', max_length=50, null=True)),
                ('vol3', models.CharField(blank=True, db_column='annual_volume_3', max_length=50, null=True)),
                ('year3', models.CharField(blank=True, db_column='annual_volume_year_3', max_length=50, null=True)),
                ('vol4', models.CharField(blank=True, db_column='annual_volume_4', max_length=50, null=True)),
                ('year4', models.CharField(blank=True, db_column='annual_volume_year_4', max_length=50, null=True)),
                ('vol5', models.CharField(blank=True, db_column='annual_volume_5', max_length=50, null=True)),
                ('year5', models.CharField(blank=True, db_column='annual_volume_year_5', max_length=50, null=True)),
                ('est_price', models.FloatField(blank=True, db_column='part_price_1', null=True)),
                ('est_val', models.FloatField(blank=True, db_column='estimated_value', null=True)),
                ('euro_conv', models.FloatField(blank=True, db_column='estimated_euro_conv', null=True)),
                ('life_cycle', models.CharField(blank=True, db_column='life_cycle_in_years', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('quote_status', models.CharField(blank=True, db_column='quotestatus', max_length=50, null=True)),
                ('cat_type', models.CharField(blank=True, db_column='categorytype', max_length=50, null=True)),
                ('modified_date', models.DateField(blank=True, db_column='last_modified_date', null=True)),
            ],
            options={
                'db_table': 'tbl_opportunitymaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityMasterECN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(db_column='item_no', max_length=50)),
                ('ecn_id', models.CharField(db_column='ecn_id', max_length=50)),
            ],
            options={
                'db_table': 'tbl_opportunitymaster_ecn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OppSalesCycles',
            fields=[
                ('code', models.CharField(db_column='Code', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('probability_calculation', models.CharField(db_column='Probability_Calculation', max_length=100)),
            ],
            options={
                'db_table': 'tbl_oppsalescycles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OppSalesPeople',
            fields=[
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'tbl_oppsalespeople',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OppSegment',
            fields=[
                ('no', models.CharField(db_column='no', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=255)),
            ],
            options={
                'db_table': 'tbl_oppsegment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=255, null=True)),
                ('customerName', models.CharField(blank=True, max_length=255, null=True)),
                ('contactName', models.CharField(blank=True, max_length=255, null=True)),
                ('contactNo', models.CharField(blank=True, max_length=20, null=True)),
                ('itemNo', models.CharField(blank=True, max_length=100, null=True)),
                ('custId', models.CharField(blank=True, max_length=100, null=True)),
                ('estimatedSalesPrice', models.FloatField(default=0)),
                ('nominatedPrice', models.FloatField(default=0)),
                ('creationDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
