# Generated by Django 4.2.9 on 2026-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feasibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('enq_no', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=255)),
                ('application', models.CharField(max_length=255)),
                ('projected_volume', models.CharField(max_length=100)),
                ('initial_date', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('feasibility_no', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('daily_peak', models.CharField(max_length=100)),
                ('sop_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=100, unique=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
            ],
        ),
    ]
