# Generated by Django 4.2.9 on 2026-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('no', models.CharField(db_column='no', max_length=100, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_column='customerid', max_length=100)),
                ('customer_name', models.CharField(db_column='customername', max_length=255)),
            ],
            options={
                'db_table': 'tbl_itemcard',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OpportunityMaster',
        ),
        migrations.AlterModelOptions(
            name='feasibility',
            options={'managed': False},
        ),
    ]
