# Generated by Django 4.2.9 on 2026-03-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('no', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('shelf_no', models.CharField(blank=True, max_length=50, null=True)),
                ('item_category_code', models.CharField(blank=True, max_length=50, null=True)),
                ('product_group_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_group_code', models.CharField(blank=True, max_length=50, null=True)),
                ('revision_no', models.CharField(blank=True, max_length=50, null=True)),
                ('template_name', models.CharField(blank=True, max_length=50, null=True)),
                ('monthyear', models.CharField(blank=True, max_length=20, null=True)),
                ('fy', models.CharField(blank=True, max_length=20, null=True)),
                ('quarter', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
