# Generated by Django 4.2.9 on 2026-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_creation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcard',
            name='shelf_no',
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='base_unit_of_measure',
            field=models.CharField(blank=True, db_column='Base_Unit_of_Measure', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='customer_id',
            field=models.CharField(db_column='CustomerID', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='customer_name',
            field=models.CharField(db_column='CustomerName', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='fy',
            field=models.CharField(blank=True, db_column='FY', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='gst_group_code',
            field=models.CharField(blank=True, db_column='GST_Group_Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='hsn_sac_code',
            field=models.CharField(blank=True, db_column='HSN_SAC_Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='item_category_code',
            field=models.CharField(blank=True, db_column='Item_Category_Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='monthyear',
            field=models.CharField(blank=True, db_column='MonthYear', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='no',
            field=models.CharField(db_column='No', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='product_group_code',
            field=models.CharField(blank=True, db_column='Product_Group_Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='quarter',
            field=models.CharField(blank=True, db_column='Quarter', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='revision_no',
            field=models.CharField(blank=True, db_column='Revision_No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='template_name',
            field=models.CharField(blank=True, db_column='Template_Name', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='itemcard',
            table='tbl_itemcard',
        ),
    ]
