# Generated by Django 4.2.9 on 2026-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_creation', '0002_remove_itemcard_shelf_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcard',
            name='base_unit_of_measure',
            field=models.CharField(blank=True, db_column='base_unit_of_measure', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='customer_id',
            field=models.CharField(db_column='customerid', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='customer_name',
            field=models.CharField(db_column='customername', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='fy',
            field=models.CharField(blank=True, db_column='fy', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='gst_group_code',
            field=models.CharField(blank=True, db_column='gst_group_code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='hsn_sac_code',
            field=models.CharField(blank=True, db_column='hsn_sac_code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='item_category_code',
            field=models.CharField(blank=True, db_column='item_category_code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='monthyear',
            field=models.CharField(blank=True, db_column='monthyear', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='no',
            field=models.CharField(db_column='no', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='product_group_code',
            field=models.CharField(blank=True, db_column='product_group_code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='quarter',
            field=models.CharField(blank=True, db_column='quarter', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='revision_no',
            field=models.CharField(blank=True, db_column='revision_no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcard',
            name='template_name',
            field=models.CharField(blank=True, db_column='template_name', max_length=50, null=True),
        ),
    ]
