# Generated by Django 4.2.9 on 2026-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_creation', '0004_applytemplate_alter_itemcard_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_cell',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_celltype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_itemcard_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('def_gen_prod_posting_group', models.CharField(db_column='def_gen_prod_posting_group', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_itemcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_productgroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('code', models.CharField(db_column='code', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=255)),
            ],
            options={
                'db_table': 'tbl_unitsofmeasure',
                'managed': False,
            },
        ),
    ]
