# Generated by Django 4.2.9 on 2026-03-18 18:02

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('customer_creation', '0002_customer_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerInfo',
        ),
        migrations.AlterModelTable(
            name='customerinfo',
            table='tbl_customerinfo',
        ),
    ]
