# Generated by Django 4.2.9 on 2026-03-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_creation', '0003_rename_customer_customerinfo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'managed': False},
        ),
    ]
